// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebmiuqrdzzdliupgcqsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVibWl1cXJkenpkbGl1cGdjcXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzYyNzQsImV4cCI6MjA2ODUxMjI3NH0.Ayq9GzSfcpERcoXSE2xu7Gk4GZQp94wRqPpe7e8bPq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});